### ISSUE TITLE
Trouble with old mint on new site

### ISSUE THREAD

**Issue by mariaa144** [cashubtc/cashu.me#166]
I'm getting errors when switching to a mint. Also, another computer with only my mint cannot receive or send money. No balance is showing.

I have an old mint version I'm running on Voltage. They won't update LNBits the last time I checked.

Is it possible for me to use the legacy site?

Here is a screenshot of the error I'm seeing.
![Screenshot from 2024-05-19 18-29-19](https://github.com/cashubtc/cashu.me/assets/105451387/68b2f20c-9f17-497d-8798-64633a4e0fc9)

LNbits version: 0.10.9, Commit version: e13426a56b579d228e83e59726f5ec8f75846ffe
LNbitsCashu/0.2.6

**Comment by callebtc** [comment]
This bug should be resolved, please feel free to reopen the issue if it pops up.

**Comment by mariaa144** [comment]
Still an issue for me. Try to test with my old mint here: https://404fddc177.d.voltageapp.io/cashu/api/v1/bd4G693GFUjCnEFPnPRfLj
